package me.josh.cubits.playerdata;

import me.josh.cubits.items.ItemBase;

public enum PlayerVariables {
    SHINY_CHARMS,
    MUSHROOMS_FOUND,
    IF_STARTER,


    STAT_FARMING,
    STAT_FORAGING,
    STAT_ADVENTURING,
    STAT_MINING,
    STAT_FISHING,
    STAT_MAGIC,
    STAT_ALCHEMY,
    STAT_CRAFTING,
    STAT_COOKING,
    STAT_SLAYER,


    FAVOR_FISHERMAN,
    FAVOR_BOBA,
    FAVOR_MUSHROOMMAN,
    FAVOR_MUSHROOM_QUEST,
    FAVOR_GENERALSHOP,
    FAVOR_SELLSHOP,
    FAVOR_DAILY_FISHERMAN,
    FAVOR_DESERT_TRADER,
    FAVOR_TUNDRA_TRADER,
    FAVOR_WANDERING_TRADER,
    FAVOR_CUSIOSITY_SHOP,
    FAVOR_SLAYER_SHOP,


    ACHIEVEMENT_TIER,
    ACHIEVEMENT_AMOUNT_1,
    ACHIEVEMENT_AMOUNT_2,
    ACHIEVEMENT_AMOUNT_3,
    ACHIEVEMENT_AMOUNT_4,
    ACHIEVEMENT_AMOUNT_5,
    ACHIEVEMENT_TARGET_AMOUNT_1,
    ACHIEVEMENT_TARGET_AMOUNT_2,
    ACHIEVEMENT_TARGET_AMOUNT_3,
    ACHIEVEMENT_TARGET_AMOUNT_4,
    ACHIEVEMENT_TARGET_AMOUNT_5,


    SLAYER_COMPLETED,
    SLAYER_STREAK,
    SLAYER_AMOUNT,
    SLAYER_TARGET_AMOUNT,
    SLAYER_ORIGINAL_TARGET_AMOUNT,
    SLAYER_POINTS_REWARD,


    FISH_CAUGHT,
    FISHING_QUEST_SPECIES,
    FISHING_QUEST_AMOUNT,
    FISHING_QUEST_TARGET_AMOUNT,
    FISHING_QUEST_ORIGINAL_AMOUNT,
    FISHING_QUEST_REWARD,
    FISHING_STREAK,
    FISHING_QUESTS_COMPLETE,


    QUESTS_COMPLETED,
    QUEST_AMOUNT_1,
    QUEST_TARGET_AMOUNT_1,
    QUEST_TYPE_1,
    QUEST_ID_1,
    QUEST_AMOUNT_2,
    QUEST_TARGET_AMOUNT_2,
    QUEST_TYPE_2,
    QUEST_ID_2,
    QUEST_AMOUNT_3,
    QUEST_TARGET_AMOUNT_3,
    QUEST_TYPE_3,
    QUEST_ID_3,


    LUCKY_POTION,
    BOUNTIFUL_POTION,
    MIDUS_POTION,
    CHEF_POTION,
    EXPERIENCE_POTION,
    TREASURE_POTION,
    SHINY_POTION,
    SLAYER_POTION,
    CRUSADER_POTION,
    PROSPECTOR_POTION,
    CHAOS_POTION,
    ANGLER_POTION




}
