package me.josh.cubits.playerdata;

public enum PlayerUpgrades {
    SLAYER_UPGRADE_SPIDER_SQUASHER,
    SLAYER_UPGRADE_DRAGON,
    SLAYER_UPGRADE_WITHER,
    SLAYER_UPGRADE_ELDERGUARDIAN,
    SLAYER_UPGRADE_WARDEN,
    SLAYER_UPGRADE_BOSSRUSH,
    SLAYER_UPGRADE_POINTBOOST,

    FISHING_UPGRADE_GEM_FINDER,
    FISHING_UPGRADE_DRESSED_SPINNER,
    FISHING_UPGRADE_TREASURE_LURE,
    FISHING_UPGRADE_DOUBLE_HAUL,
    FISHING_UPGRADE_FISHING_FRENZY,
    FISHING_UPGRADE_SCAVANGER,
    FISHING_UPGRADE_TITANIUM_LURE,
    FISHING_UPGRADE_PRESERVE_LURE
}
